### ISSUE TITLE
Mini Controller Implementation Should Use "High Resolution" Mode

### ISSUE THREAD

**Issue by dmadison** [dmadison/NintendoExtensionCtrl#60]
As @nullstalgia discovered in #56 ([link](https://github.com/dmadison/NintendoExtensionCtrl/pull/56#issuecomment-601941705)), the NES Mini and SNES Mini controllers use a special "high resolution" mode of the Classic Controller for sending data. This is why knockoff NES Mini controllers were reporting their data incorrectly - they assume that the high resolution mode has already been enabled by the console (i.e. Arduino) even when it wasn't.

It would be better to implement this properly, writing the "high res" register if the mode is called for and not trying to "fix" the data by shifting it in the array after it has been received. It's cleaner, more robust, and would have the same data outputs for both OEM and 3rd party controllers.

Setting the "high resolution" mode is accomplished by writing `0x03` to address `0xFE`.

Standard data format:
```
		7	6	5	4	3	2	1	0
	0	RX<4:3>	LX<5:0>
	1	RX<2:1>	LY<5:0>
	2	RX<0>	LT<4:3>	RY<4:0>
	3	LT<2:0>	RT<4:0>
	4	BDR	BDD	BLT	B-	BH	B+	BRT	1
	5	BZL	BB	BY	BA	BX	BZR	BDL	BDU
```

High resolution data format:
```
		7	6	5	4	3	2	1	0
	0	LX<7:0>
	1	RX<7:0>
	2	LY<7:0>
	3	RY<7:0>
	4	LT<7:0>
	5	RT<7:0>
	6	BDR	BDD	BLT	B-	BH	B+	BRT	1
	7	BZL	BB	BY	BA	BX	BZR	BDL	BDU
```
[Source](https://github.com/raphnet/extenmote/blob/61b8af2048d2e7665aec09676efb9d1e4f42021e/notes_nes_classic.txt)

**Comment by nullstalgia** [comment]
Suggestion: Change title to

"Mini Controllers (implementation?) *should* use 'High Resolution' Mode" since it sounds like the actual controllers don't use the mode, not the library itself
