### ISSUE TITLE
Non genuine classic controller not initialised with classic.begin(); but can get data with controller.begin();

### ISSUE THREAD

**Issue by joshhh** [dmadison/NintendoExtensionCtrl#68]
Trying to find out what's wrong with my XBOX controller emulation on chinese arduino micro 32u4 board mimicking as leonardo board

Always get Controller not detected with classic.begin(); but can get data with controller.begin();

All RAW data from controller detected in serial monitor, so it is working. 

Also everything is working with Leonardo WiiClassicController GamePad by Nguyen Chi Tam

**Comment by dmadison** [comment]
A few questions:
* Which examples are working? Which examples are not?
* What controller are you using (make and model)?
* Are you using a breakout board? If so, which?
* What are your hardware connections to the controller?
* With `classic.begin()` returning false, are you still able to get data in subsequent requests?

**Comment by joshhh** [comment]
DebugPrint.ino is working 100% with all raw data visible and reacting on button-pads 
Classic_DebugPrint.ino get Classic Controller not detected all the time


Arduino board https://www.aliexpress.com/item/32890044536.html
Classic controller clone  https://www.aliexpress.com/item/1005001430909586.html

No breakout boards are used.  Only diy pcb as connector to wii controller and direct soldering to SDA, SCL, GND, VCC

With classic.begin() I get Classic Controller not detected
With controller.begin(); I get raw data...

**Comment by dmadison** [comment]
Hmm. When used as a `ClassicController` object the code jumps through a few hoops to get both Classic Controllers and NES / SNES Mini controllers to behave the same. If it's falling the 'connect' check as a `ClassicController` but working as a generic one then that controller-specific initialization must be failing for some reason, which it should only do if the I²C functions report a problem. Your clone controller is probably not behaving like the genuine ones and doing something it's not supposed to.

If you run the Classic Controller example but ignore the result of the `connect()` call it should work, but that's not a great solution.

Try adding this block to the `DebugPrint` example, after the `connect()` call:

```
  if(controller.writeRegister(0xFE, 0x03)) {
     Serial.println("Successful register write");
  }
  else {
    Serial.println("Failed register write");
  }
```

Run that and let me know the output.

Then replace it with this, in the same place after the `connect()` call, and run it as well:
```
  uint8_t temp[8];
  if(controller.requestData(0x00, 8, temp)) {
     Serial.println("Successful read");
  }
  else {
     Serial.println("Failed read");
  }
```

One of the two, possibly both, is probably failing.

**Comment by joshhh** [comment]
First code inside void loop() sequence receive this

```
15:09:09.467 -> Failed register write
15:09:09.467 -> Raw[6]: 0xA0 0x20 0x10 0x00 0xFF 0xFF
```

Second 

```
15:09:21.599 -> Successful read
15:09:21.599 -> Raw[6]: 0xA0 0x20 0x10 0x00 0xFF 0xFF
```

So first one cause it is fail to connect

**Comment by dmadison** [comment]
Okay great, thanks. I'll have to do some thinking about how best to implement a workaround for that.

If you could, in the same place try these two lines:

    controller.writeRegister(0xFE, 0x03);
    controller.setRequestSize(8);

And please post the output from the first 'Raw' debug message.

**Comment by joshhh** [comment]
Got this. last two bytes are zeroes 

`#include <NintendoExtensionCtrl.h>

ExtensionPort controller;

void setup() {
	Serial.begin(115200);
	controller.begin();

	while (!controller.connect()) {
		Serial.println("Controller not detected!");
		delay(1000);
	}
}

void loop() {
	boolean success = controller.update();  // Get new data from the controller

	controller.writeRegister(0xFE, 0x03);
	controller.setRequestSize(8);
	delay(100);

	if (success == true) {  // We've got data!
		controller.printDebugRaw();  // Print all of the values!
	}
	else {  // Data is bad :(
		Serial.println("Controller Disconnected!");
		delay(1000);
		controller.connect();
	}
}`

`18:04:58.595 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:58.707 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:58.819 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:58.925 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:58.992 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.098 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.208 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.320 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.428 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.539 -> Raw[8]: 0x80 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.611 -> Raw[8]: 0x80 0x0C 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.717 -> Raw[8]: 0x80 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.824 -> Raw[8]: 0xA0 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:04:59.930 -> Raw[8]: 0xA0 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.036 -> Raw[8]: 0xBF 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.145 -> Raw[8]: 0xBF 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.250 -> Raw[8]: 0xBF 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.357 -> Raw[8]: 0xA2 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.461 -> Raw[8]: 0xA0 0x38 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.529 -> Raw[8]: 0x81 0x3D 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.637 -> Raw[8]: 0x80 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.743 -> Raw[8]: 0x80 0x0F 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.848 -> Raw[8]: 0x80 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:00.954 -> Raw[8]: 0x60 0x80 0x17 0x00 0xFF 0xFF 0x00 0x00
18:05:01.065 -> Raw[8]: 0x3F 0x00 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:01.170 -> Raw[8]: 0x3F 0x00 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:01.275 -> Raw[8]: 0x3F 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:01.381 -> Raw[8]: 0x7F 0x20 0x80 0x00 0xFF 0xFF 0x00 0x00
18:05:01.489 -> Raw[8]: 0xFB 0xF3 0x80 0x00 0xFF 0xFF 0x00 0x00
18:05:01.560 -> Raw[8]: 0xE0 0xF8 0x90 0x00 0xFF 0xFF 0x00 0x00
18:05:01.667 -> Raw[8]: 0xC1 0xEF 0x9F 0x00 0xFF 0xFF 0x00 0x00
18:05:01.774 -> Raw[8]: 0x80 0x55 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:01.880 -> Raw[8]: 0xA0 0x00 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:01.987 -> Raw[8]: 0x3B 0x00 0x1D 0x00 0xFF 0xFF 0x00 0x00
18:05:02.089 -> Raw[8]: 0x3F 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:02.195 -> Raw[8]: 0x3F 0x20 0x00 0x00 0xFF 0xFF 0x00 0x00
18:05:02.302 -> Raw[8]: 0xF0 0xE8 0x85 0x00 0xFF 0xFF 0x00 0x00
18:05:02.407 -> Raw[8]: 0xE0 0xFC 0x90 0x00 0xFF 0xFF 0x00 0x00
18:05:02.482 -> Raw[8]: 0xC0 0xE0 0x9F 0x00 0xFF 0xFF 0x00 0x00
18:05:02.588 -> Raw[8]: 0x80 0x00 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:02.693 -> Raw[8]: 0x20 0x00 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:02.800 -> Raw[8]: 0x3F 0x00 0x11 0x00 0xFF 0xFF 0x00 0x00
18:05:02.911 -> Raw[8]: 0x3F 0x06 0x07 0x00 0xFF 0xFF 0x00 0x00
18:05:03.021 -> Raw[8]: 0xA0 0x20 0x00 0x00 0xFF 0xFF 0x00 0x00
18:05:03.125 -> Raw[8]: 0xCE 0xFF 0x82 0x00 0xFF 0xFF 0x00 0x00
18:05:03.236 -> Raw[8]: 0xC1 0xFF 0x90 0x00 0xFF 0xFF 0x00 0x00
18:05:03.304 -> Raw[8]: 0xC0 0xF4 0x9F 0x00 0xFF 0xFF 0x00 0x00
18:05:03.411 -> Raw[8]: 0xA0 0x20 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:03.517 -> Raw[8]: 0xA0 0x20 0x7F 0xFF 0x9D 0xFD 0x00 0x00
18:05:03.629 -> Raw[8]: 0x60 0x60 0x7F 0xFF 0xDD 0xFD 0x00 0x00
18:05:03.737 -> Raw[8]: 0x20 0x60 0xFF 0xFF 0xDD 0xFF 0x00 0x00
18:05:03.844 -> Raw[8]: 0x20 0x60 0xFF 0xE0 0xDF 0xFF 0x00 0x00
18:05:03.952 -> Raw[8]: 0x20 0x60 0xFF 0xE0 0xDF 0x7B 0x00 0x00
18:05:04.024 -> Raw[8]: 0x20 0xE0 0x9F 0x1F 0xFD 0x7F 0x00 0x00
18:05:04.134 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0x7F 0x00 0x00
18:05:04.239 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0xFF 0x00 0x00
18:05:04.344 -> Raw[8]: 0xA0 0x20 0x70 0xE0 0xDF 0xFF 0x00 0x00
18:05:04.452 -> Raw[8]: 0xA0 0x20 0x70 0xE0 0xDF 0x7F 0x00 0x00
18:05:04.558 -> Raw[8]: 0xA0 0x20 0x10 0x1F 0xFD 0x3D 0x00 0x00
18:05:04.666 -> Raw[8]: 0xA0 0x20 0x10 0x1F 0xBD 0x9D 0x00 0x00
18:05:04.771 -> Raw[8]: 0xA0 0x20 0x10 0x1F 0xBD 0x9B 0x00 0x00
18:05:04.846 -> Raw[8]: 0xA0 0x20 0x10 0x1F 0x3D 0x9B 0x00 0x00
18:05:04.952 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0x1D 0xBB 0x00 0x00
18:05:05.057 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0x29 0x00 0x00
18:05:05.163 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0x61 0x00 0x00
18:05:05.272 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0x65 0x00 0x00
18:05:05.383 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0xBF 0x00 0x00
18:05:05.489 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xBF 0x00 0x00
18:05:05.596 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xBB 0x00 0x00
18:05:05.666 -> Raw[8]: 0xA0 0x20 0x70 0xE0 0x5F 0xBB 0x00 0x00
18:05:05.768 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0x5D 0xBB 0x00 0x00
18:05:05.881 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0xAA 0x00 0x00
18:05:05.987 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0xA0 0x00 0x00
18:05:06.096 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0xB1 0x00 0x00
18:05:06.202 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0x1D 0x9F 0x00 0x00
18:05:06.312 -> Raw[8]: 0xA0 0x20 0x70 0xE0 0x5F 0x9F 0x00 0x00
18:05:06.417 -> Raw[8]: 0xA0 0x20 0x70 0xE0 0x5F 0xBF 0x00 0x00
18:05:06.489 -> Raw[8]: 0xA0 0x20 0x70 0xE0 0x5F 0xFF 0x00 0x00
18:05:06.595 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:06.696 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:06.802 -> Raw[8]: 0x34 0x40 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:06.915 -> Raw[8]: 0x3F 0x00 0x1F 0x00 0xFF 0xFF 0x00 0x00
18:05:07.021 -> Raw[8]: 0x3F 0x00 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:07.128 -> Raw[8]: 0xBF 0x00 0x00 0x00 0xFF 0xFF 0x00 0x00
18:05:07.235 -> Raw[8]: 0xCD 0xE0 0x80 0x00 0xFF 0xFF 0x00 0x00
18:05:07.337 -> Raw[8]: 0xC0 0xE0 0x90 0x00 0xFF 0xFF 0x00 0x00
18:05:07.445 -> Raw[8]: 0x94 0x00 0x1F 0x00 0xFF 0xFB 0x00 0x00
18:05:07.517 -> Raw[8]: 0xBF 0x00 0x1F 0x00 0xFF 0xFB 0x00 0x00
18:05:07.630 -> Raw[8]: 0x3F 0x20 0x1F 0x1F 0xFD 0xFF 0x00 0x00
18:05:07.738 -> Raw[8]: 0xA9 0x3F 0x70 0xFF 0xDD 0x7F 0x00 0x00
18:05:07.848 -> Raw[8]: 0xA0 0x3F 0x70 0xFF 0xDD 0x7B 0x00 0x00
18:05:07.956 -> Raw[8]: 0x80 0x29 0x7F 0xE0 0xDF 0x7B 0x00 0x00
18:05:08.060 -> Raw[8]: 0x80 0xE0 0x1F 0x00 0xFF 0x7B 0x00 0x00
18:05:08.133 -> Raw[8]: 0xC0 0xC0 0xF0 0xE0 0xDF 0xFF 0x00 0x00
18:05:08.241 -> Raw[8]: 0xFF 0xC0 0xF0 0xE0 0xDF 0xFF 0x00 0x00
18:05:08.347 -> Raw[8]: 0x7F 0x20 0x6A 0xE0 0xDF 0xFF 0x00 0x00
18:05:08.455 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xDD 0xFF 0x00 0x00
18:05:08.566 -> Raw[8]: 0xA0 0x20 0x10 0x1F 0xFD 0xFF 0x00 0x00
18:05:08.671 -> Raw[8]: 0xA0 0x20 0x70 0xFF 0xC9 0xFF 0x00 0x00
18:05:08.776 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xEB 0xFF 0x00 0x00
18:05:08.849 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFB 0xFF 0x00 0x00
18:05:08.957 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:09.062 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:09.172 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:09.280 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:09.388 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xF3 0xFF 0x00 0x00
18:05:09.491 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xF3 0xFF 0x00 0x00
18:05:09.602 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:09.678 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:09.783 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xF7 0xFF 0x00 0x00
18:05:09.892 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:09.997 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:10.105 -> Raw[8]: 0xA0 0x20 0x10 0x1F 0xF9 0xFF 0x00 0x00
18:05:10.210 -> Raw[8]: 0xA0 0x20 0x10 0x1F 0xF1 0xFB 0x00 0x00
18:05:10.318 -> Raw[8]: 0xA0 0x20 0x70 0xE0 0xDF 0xFB 0x00 0x00
18:05:10.392 -> Raw[8]: 0x89 0x04 0x72 0xE0 0xDF 0xFF 0x00 0x00
18:05:10.498 -> Raw[8]: 0xC0 0xC0 0xF6 0xE0 0xDF 0xFF 0x00 0x00
18:05:10.604 -> Raw[8]: 0xD1 0xCA 0xF0 0xE0 0xDF 0xFF 0x00 0x00
18:05:10.712 -> Raw[8]: 0xA0 0x3F 0x70 0xE0 0xDF 0xFF 0x00 0x00
18:05:10.817 -> Raw[8]: 0xA0 0x3F 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:10.925 -> Raw[8]: 0xA0 0x3F 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.026 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.134 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.246 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.314 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.427 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.536 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.642 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.752 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.857 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:11.963 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:12.036 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:12.141 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:12.253 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:12.358 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
18:05:12.468 -> Raw[8]: 0xA0 0x20 0x10 0x00 0xFF 0xFF 0x00 0x00
`

**Comment by dmadison** [comment]
Great, that's exactly what it should be reporting. That means that while it NACK's the request to set the data mode because it doesn't understand it, it still reports its data in a way that we can figure out what mode it's in.

I've added a patch to the [`classic-clone-fix` branch](../tree/classic-clone-fix). Please download and test that to see if it fixes the issue.

**Comment by joshhh** [comment]
Confirmed. It is working now and output to serial monitor all pressed buttons events. Also XInput XBOX controller code also works now in control panel and other applications

**Comment by dmadison** [comment]
Fantastic. Thanks for reporting the issue and I'm glad I was able to fix it for you. I'll merge those changes and push out a new release of the library.

Have fun with the controller!
